### ISSUE TITLE
Write up a full 'how to make this as awesome as possible' in the readme

### ISSUE THREAD

**Issue by robcowell** [forcedotcom/Codeys-in-bed-by-10#2]
_"Feel free to file an issue here if you'd like me to write up a full 'how to make this as awesome as possible' in the readme"_ - **codefriar**

In order to help folks attain the look and feel from your screenshots, please can you add a supplemental section to the README on other plugins/settings used on VSCode

**Comment by codefriar** [comment]
@robcowell - I launched Codefriar's Pack today - an extension pack to get you setup and sorted quick as a gif. 

https://marketplace.visualstudio.com/items?itemName=codefriar.codefriar-s-pack
