### ISSUE TITLE
Selected text highlight colour contrast

### ISSUE THREAD

**Issue by robcowell** [forcedotcom/Codeys-in-bed-by-10#5]
Can we make selected text background colour contrast a little less subtle?

![image](https://user-images.githubusercontent.com/2143167/105873347-4ab50100-5ff3-11eb-89c4-24158af710a2.png)

**Comment by codefriar** [comment]
Hey @robcowell do you have suggestions on what you'd like that color to be?

**Comment by robcowell** [comment]
I think *base* color probably needs to stay the same, given the wide variance in the color of the text it is highlighting, just wondering if playing with the contrast levels may make it more distinct from the underlying background..  I'll maybe try and dabble with it later and see if I find something that fits my tired old eyes

**Comment by codefriar** [comment]
I was actually thinking of desaturating it. making the highlight go full black. let me experiment

**Comment by codefriar** [comment]
@robcowell  How do you feel about this: (#a03286e2)

![image](https://user-images.githubusercontent.com/642589/106172498-e1530080-6160-11eb-9f7b-ea434052ec89.png)

**Comment by robcowell** [comment]
I'm good with that bin so much as it's very clear which section is highlighted. Even the word string, despite being purple on purple.

**Comment by codefriar** [comment]
@robcowell - just published a new version, should be live in just a few minutes.
